Algoritmo "semnome"
// Disciplina   : internet e programação web
// Professor   : reisalan94
// Descrição   :algoritmos de teste
// Autor(a)    : Alan lenon dos reis
// Data atual  : 22/09/2022
Var
// Seção de Declarações das variáveis 
  x, y, z:inteiro ;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <-10;
   y <-5;
   z <- x + y;
   escreva(z);

Fimalgoritmo